[package]
authors = ["Domino Maintainers <maintainers@dominochain.com>"]
description = "Blockchain, Rebuilt for Scale"
edition = "2021"
homepage = "https://dominochain.com/"
license = "Apache-2.0"
name = "proto"
publish = false
repository = "https://github.com/Domino-Blockchain/domino"
version = "1.10.0"

[workspace]

[dependencies]
tonic-build = "0.6.0"
