[package]
name = "domino-compute-budget-program"
description = "Domino Compute Budget program"
version = "1.10.0"
homepage = "https://dominochain.com/"
documentation = "https://docs.rs/domino-compute-budget-program"
repository = "https://github.com/Domino-Blockchain/domino"
authors = ["Domino Maintainers <maintainers@domino.foundation>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
domino-program-runtime = { path = "../../program-runtime", version = "=1.10.0" }
domino-sdk = { path = "../../sdk", version = "=1.10.0" }

[lib]
crate-type = ["lib"]
name = "domino_compute_budget_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
