[package]
authors = ["Domino Maintainers <maintainers@domino.foundation>"]
edition = "2021"
name = "domino-watchtower"
description = "Blockchain, Rebuilt for Scale"
version = "1.10.0"
repository = "https://github.com/Domino-Blockchain/domino"
license = "Apache-2.0"
homepage = "https://dominochain.com/"
documentation = "https://docs.rs/domino-watchtower"

[dependencies]
clap = "2.33.1"
log = "0.4.14"
humantime = "2.0.1"
domino-clap-utils = { path = "../clap-utils", version = "=1.10.0" }
domino-cli-config = { path = "../cli-config", version = "=1.10.0" }
domino-cli-output = { path = "../cli-output", version = "=1.10.0" }
domino-client = { path = "../client", version = "=1.10.0" }
domino-logger = { path = "../logger", version = "=1.10.0" }
domino-metrics = { path = "../metrics", version = "=1.10.0" }
domino-notifier = { path = "../notifier", version = "=1.10.0" }
domino-sdk = { path = "../sdk", version = "=1.10.0" }
domino-version = { path = "../version", version = "=1.10.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
