[package]
name = "vrf_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
schnorrkel = {git = "https://github.com/w3f/schnorrkel.git" ,version = "0.10.2"}
rand="0.8.5"
rand_chacha="0.3.1"
rand_core= "0.6.3"