[package]
name = "domino-test-validator"
description = "Blockchain, Rebuilt for Scale"
version = "1.10.0"
homepage = "https://dominochain.com/"
documentation = "https://docs.rs/domino-test-validator"
readme = "../README.md"
repository = "https://github.com/Domino-Blockchain/domino"
authors = ["Domino Maintainers <maintainers@domino.foundation>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
base64 = "0.12.3"
log = "0.4.14"
domino-client = { path = "../client", version = "=1.10.0" }
domino-core = { path = "../core", version = "=1.10.0" }
domino-gossip = { path = "../gossip", version = "=1.10.0" }
domino-ledger = { path = "../ledger", version = "=1.10.0" }
domino-logger = { path = "../logger", version = "=1.10.0" }
domino-net-utils = { path = "../net-utils", version = "=1.10.0" }
domino-program-test = { path = "../program-test", version = "=1.10.0" }
domino-rpc = { path = "../rpc", version = "=1.10.0" }
domino-runtime = { path = "../runtime", version = "=1.10.0" }
domino-sdk = { path = "../sdk", version = "=1.10.0" }
domino-streamer = { path = "../streamer", version = "=1.10.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
