[package]
authors = ["Domino Maintainers <maintainers@domino.foundation>"]
description = "Domino Program Test Framework"
edition = "2021"
license = "Apache-2.0"
name = "domino-program-test"
repository = "https://github.com/Domino-Blockchain/domino"
version = "1.10.0"

[dependencies]
async-trait = "0.1.52"
base64 = "0.12.3"
bincode = "1.3.3"
chrono-humanize = "0.2.1"
log = "0.4.14"
serde = "1.0.131"
domino-banks-client = { path = "../banks-client", version = "=1.10.0" }
domino-banks-server = { path = "../banks-server", version = "=1.10.0" }
domino-bpf-loader-program = { path = "../programs/bpf_loader", version = "=1.10.0" }
domino-logger = { path = "../logger", version = "=1.10.0" }
domino-program-runtime = { path = "../program-runtime", version = "=1.10.0" }
domino-runtime = { path = "../runtime", version = "=1.10.0" }
domino-sdk = { path = "../sdk", version = "=1.10.0" }
domino-vote-program = { path = "../programs/vote", version = "=1.10.0" }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
assert_matches = "1.5.0"
