[package]
name = "domino-upload-perf"
version = "1.10.0"
description = "Metrics Upload Utility"
authors = ["Domino Maintainers <maintainers@domino.foundation>"]
repository = "https://github.com/Domino-Blockchain/domino"
license = "Apache-2.0"
edition = "2021"
homepage = "https://dominochain.com/"
publish = false

[dependencies]
serde_json = "1.0.73"
domino-metrics = { path = "../metrics", version = "=1.10.0" }

[[bin]]
name = "domino-upload-perf"
path = "src/upload-perf.rs"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
