[package]
name = "domino-bpf-rust-dep-crate"
version = "1.10.0"
description = "Domino BPF test program written in Rust"
authors = ["Domino Maintainers <maintainers@domino.foundation>"]
repository = "https://github.com/Domino-Blockchain/domino"
license = "Apache-2.0"
homepage = "https://dominochain.com/"
documentation = "https://docs.rs/domino-bpf-rust-dep-crate"
edition = "2021"

[dependencies]
byteorder = { version = "1", default-features = false }
domino-program = { path = "../../../../sdk/program", version = "=1.10.0" }

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
